export const ApiConfig = {
  baseUrl: import.meta.env.VITE_PUBLIC_API_URL,
  gameType: "game_types",
  paymentProvider: "agentPaymentType",
  user: "user",
  gameProduct: "gameTypeProducts",
  gameList: "gamelist",
  gameLogs: "wager-logs",
  hotGames: "hotgamelist",
  getGameInfo: "GameLogin",
  promotion: "promotion",
  deposit: "deposit",
  depositHistory: "depositlog",
  withdrawHistory: "withdrawlog",
  withdraw: "withdraw",
  login: "login",
  register: "register",
  logout: "logout",
  changePassword: "change-password",
  videoAds: "videoads",
  contact: "contact",
  banner: "banner",
  bannerText: "banner_Text",
  bet: "bet",
  launchGame: "GameLogin",
};
